"""Make Family name column unique

Revision ID: 0294d7f5b5d4
Revises: 9275818511a2
Create Date: 2025-03-05 18:48:15.193303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0294d7f5b5d4'
down_revision: Union[str, None] = '9275818511a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_family_name', table_name='family')
    op.create_index(op.f('ix_family_name'), 'family', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_family_name'), table_name='family')
    op.create_index('ix_family_name', 'family', ['name'], unique=False)
    # ### end Alembic commands ###
