"""Add created_by_user_id and last_modified_by_user_id for families table

Revision ID: 4c1bf69707f7
Revises: 0cae0f10dad7
Create Date: 2025-03-15 22:49:22.571684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1bf69707f7'
down_revision: Union[str, None] = '0cae0f10dad7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('created_by_user_id', sa.Integer(), nullable=False))
    op.add_column('families', sa.Column('last_modified_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'families', 'users', ['last_modified_by_user_id'], ['id'])
    op.create_foreign_key(None, 'families', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_constraint(None, 'families', type_='foreignkey')
    op.drop_column('families', 'last_modified_by_user_id')
    op.drop_column('families', 'created_by_user_id')
    # ### end Alembic commands ###
