"""Add timestamps and softdelete columns to families

Revision ID: 6628f45a035c
Revises: 0294d7f5b5d4
Create Date: 2025-03-05 20:21:55.151478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '6628f45a035c'
down_revision: Union[str, None] = '0294d7f5b5d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('family', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('family', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family', 'updated_at')
    op.drop_column('family', 'created_at')
    op.drop_column('family', 'deleted_at')
    # ### end Alembic commands ###
